# Generated by Django 6.0.6 on 2026-07-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pes', '0002_transactions_result_desc_transactions_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='transactions',
            name='checkout_request_id',
            field=models.CharField(default='Testing', max_length=100),
        ),
        migrations.AddField(
            model_name='transactions',
            name='merchant_request_id',
            field=models.CharField(default='Testing', max_length=100),
        ),
    ]
