# Generated by Django 6.0.6 on 2026-07-15 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pes', '0003_rename_phone_transactions_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number.', regex='^(?:2547\\d{8}|07\\d{8})$')]),
        ),
    ]
