# Generated by Django 6.0.6 on 2026-07-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pes', '0005_transactions_created_at_transactions_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='response_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='response_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
