# Generated by Django 6.0.6 on 2026-07-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pes', '0006_transactions_response_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
