# Generated by Django 6.0.6 on 2026-07-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pes', '0007_transactions_is_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='is_success',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
